# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bbe07f3bac4dda3e42aebe343e5537bb323e4e352a09654e600452fec60c552cae690f9386ae5f47acac3e9a2f4bd06e85b4333e5996d35fa70e28a7705f0cc

test:
  secret_key_base: 3d8cc49352b34a4d7951dbc34621ec67a765cb72ab86da3b12f1c17093306c4e2f372a95dde257976c1adfad3fc9f993b10ddd7282e3f0b5687a26d0775dd430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
